version: '3'

tasks:
  proto:
    desc: "Generate Go code from Protobuf files"
    cmds:
      - protoc -I ./api/grpc --go_out=pkg/grpc --go_opt=paths=source_relative --go-grpc_out=pkg/grpc --go-grpc_opt=paths=source_relative api/grpc/*.proto
  migrateCreate:
    desc: "Create migration files"
    cmds:
      - goose -dir=migrations create {{ .name }} sql
  migrateUp:
    cmds:
      - source .env && goose -dir=migrations postgres "postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable" up
  migrateDown:
    cmds:
      - source .env && goose -dir=migrations postgres "postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable" down
  migrateStatus:
    cmds:
      - source .env && goose -dir=migrations postgres "postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable" status
  testList:
    cmds:
      - ghz --config ./test/load/file_list_service_test.json --insecure localhost:50051
  testUpload:
    cmds:
      - ghz --config ./test/load/file_upload_service_test.json --insecure localhost:50051